### ISSUE TITLE
groupComparison() Issue in ComparisonResult Data Frame

### ISSUE THREAD

**Issue by kkw5710** [MeenaChoi/MSstats#111]
I have just recently updated R and RStudio to the newest current version. Prior to this update, dataProcess() and groupComparison() were both producing the expected output. dataProcess() is still functioning and is producing the same results, but now when running groupComparison(), the ComparisonResult data frame has only the Protein and Label columns with the actual (and correct) values, but every other column (i.e. log2FC, SE, Tvalue, DF, pvalue, adj.pvalue, etc.) only has NA for every observation for each protein. I am not receiving any warning or error messages with either function, and I have already tried the following to resolve this issue:

1. Ensured that I have the newest BiocManager and MSstats versions.
2. Removed and reinstalled both of these packages.
3. Verified that the dataProcess() output (the input for groupComparion()) is correct.
4. Consulted the documentation for the newest MSstats version.
5. Ensured that my data preprocessing steps and constructing of the contrast matrix are correct.

For reference, the following image is the ComparisonResult data frame produced when I run groupComparison() now (Protein and Label have actual values, while every other column has only NA for each observation):

<img width="912" alt="Screenshot 2024-02-18 092034" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/23251edd-c544-45bf-bc5d-19d9bb10cbc0">

Any assistance with this issue would be greatly appreciated.

**Comment by mstaniak** [comment]
Hi,
thank you for reporting this potential bug, could you kindly share the code that you're using and output of session_info?

**Comment by kkw5710** [comment]
I am not sure what you require, but this is my ProteinLevelData output from dataProcess(), which is producing the expected results:


<img width="923" alt="Screenshot 2024-02-20 191752" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/b9eb6987-7446-4f2b-82d2-469836939b3a">


This is the code I used after running dataProcess() for groupComparison():


<img width="511" alt="Screenshot 2024-02-20 192249" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/b5a76cbe-4847-4b2b-8ea9-724f421d9d26">
<img width="607" alt="Screenshot 2024-02-20 192305" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/0ed037cc-448d-41a7-8264-4583969d7924">


This code has not been altered in any way after updating R and RStudio and it does not result in any errors. 

Lastly, this is the output of my session_Info():

<img width="530" alt="Screenshot 2024-02-20 193402" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/73851c75-4a14-428f-9c0d-6e34b63edc78">
<img width="545" alt="Screenshot 2024-02-20 193419" src="https://github.com/Vitek-Lab/MSstats/assets/74326179/c8d60312-501f-4b9d-a385-13c09af8e5a4">


I hope this is helpful and I thank you for any assistance you can provide on this issue. Please let me know if you require any more information.

**Comment by mstaniak** [comment]
Hi,
please try re-running with option save_fitted_models set to TRUE. This way we can verify if models are fitted correctly.

**Comment by mstaniak** [comment]
Hi,
do groups labels start with digits?

**Comment by kkw5710** [comment]
Thank you for your continued help. I have run groupComparison() with "save_fitted_models = TRUE." What output do you require to assist you?

And in regards to the group labels, I have 8 labels in total - 5 of which do start with digits.

I hope this was helpful and thank you again!

**Comment by mstaniak** [comment]
Please put letters at the start of group labels, this should fix the problem.

**Comment by mstaniak** [comment]
hope it is OK now, please re-open if the problem persists

**Comment by kkw5710** [comment]
Hi. I added an 'X' to all Labels that started with a digit and that still did not fix the issue. I apologize for this continued problem, and any help would be greatly appreciated.
